# login
POST  http://localhost:5000


### lOGIN
POST  http://localhost:5000/login
Content-Type: application/json

{
"email": "test@test.com",
"password": "test"
}


### GET USERS
GET  http://localhost:5000/users/


### SIGNUP
POST  http://localhost:5000/signup
Content-Type: application/json

{
    "name": "admin",
    "email": "admn@artgram.com",
    "password": "admin",
}

### Get arts
GET http://localhost:5000/arts

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWIwMWVkNTZjNGUwNmQ3NDI5ZTg1MCIsImlhdCI6MTY3OTU4MDU0MSwiZXhwIjoxNjc5NTgxNzQxfQ.wVoxIiA5er5t7-zaUACXNOhzQYrYmFet1bOmp0VvWqU"
}